spring:
  application:
    name: ldapTest
# THYMELEAF
  thymeleaf:
    encoding: UTF-8
# 热部署静态文件
  thymeleaf:
    cache: false
  thymeleaf:
    mode: HTML5
  ldap:
    embedded:
      ldif: 127.0.0.1.389
      base-dn: dc=dinghuang,dc=com
server:
  port: 8086
logging:
  level.ldaptest.*: DEBUG